[milesmcc]
name = "Miles McCain"
website = "https://miles.land"
github = "milesmcc"
email = "privacyspy@sendmiles.email"
role = "founder"

[ibarakaiev]
name = "Igor Barakaiev"
website = "https://igor.fyi"
github = "ibarakaiev"
email = "privacyspy@igor.fyi"
role = "founder"

[doamatto]
name = "Matt"
website = "https://doamatto.xyz"
github = "doamatto"
email = "hello@doamatto.xyz"

[UnKnOwN]

[YuriiStasiuk]

[kulchynska]

[owlswipe]

[ftsell]

[nep]

[yaagesoft]

[RambosRide]

[unbeatable101]
github = "unbeatable-101"

[Anastasia]

[vutut]
github = "vutut"
email = "vutut@posteo.net"

[mrhedgehog0]

[Wingo5315]

[Q]
name = "Quintin Moss"
email = "qmoss2021@gmail.com"

[captainmeta4]
name = "Adam LaDine"
website = "https://adam.ladine.me/"
github = "captainmeta4"

[erotavlas]
name = "erotavlas"
email = "erotavlas@pm.me"
